# Hello world 

In [3]:
import tensorflow as tf
print("Tensorflow version : ", tf.__version__)

Tensorflow version :  2.15.0


# Loading Dataset

In [9]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
x_train, x_test = X_train/255 , X_test/255

# Build a machine learning model

In [10]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

Sequential is useful for stacking layers where each layer has one input tensor and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers.

For each example, the model returns a vector of logits or log-odds scores, one for each class.




In summary, the Dense layer creates fully connected layers in a neural network, while the Dropout layer helps prevent overfitting by randomly dropping out neurons during training, encouraging the network to learn more robust features. Both layers are crucial components in building effective neural networks.

In [15]:
prediction = model(x_train[:1]).numpy()
prediction

array([[ 0.57221216, -0.18794934, -0.05675144, -0.0215777 ,  0.13259645,
         0.21593043,  0.3895805 , -0.16447993,  0.12875153, -0.25866452]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:



In [16]:
tf.nn.softmax(prediction).numpy()

array([[0.15906413, 0.07437694, 0.0848041 , 0.08784006, 0.10248247,
        0.11138868, 0.13251233, 0.07614317, 0.10208919, 0.06929902]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In this line of code, you're defining a loss function for your model using TensorFlow's Keras API. Let's break it down:

`tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)`

- `tf.keras.losses`: This is the module in TensorFlow that provides various loss functions commonly used in machine learning tasks.

- `SparseCategoricalCrossentropy`: This is the specific loss function being used. It is commonly used in classification tasks where the labels are integers (i.e., sparse targets), and the model outputs raw logits (i.e., unnormalized predictions) for each class.

- `from_logits=True`: This parameter indicates that the model's output is not normalized, i.e., it's the output of the last layer before applying softmax activation. This means that the loss function will internally apply softmax to the model's output to compute probabilities before calculating the loss. If `from_logits` were `False`, it would expect the model's output to already be probabilities.

Overall, `SparseCategoricalCrossentropy` loss function with `from_logits=True` is suitable when you're dealing with classification tasks where the model outputs logits and the labels are integers representing the class indices.

In [19]:
loss_fn(y_train[:1], prediction).numpy()

2.1947296

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs = 10)

Epoch 1/10
1875/1875 [==============================] - 1s 658us/step - loss: 0.2919 - accuracy: 0.9148
Epoch 2/10
1875/1875 [==============================] - 1s 661us/step - loss: 0.1426 - accuracy: 0.9576
Epoch 3/10
1875/1875 [==============================] - 1s 684us/step - loss: 0.1078 - accuracy: 0.9673
Epoch 4/10
1875/1875 [==============================] - 1s 652us/step - loss: 0.0870 - accuracy: 0.9731
Epoch 5/10
1875/1875 [==============================] - 1s 654us/step - loss: 0.0758 - accuracy: 0.9758
Epoch 6/10
1875/1875 [==============================] - 1s 656us/step - loss: 0.0660 - accuracy: 0.9788
Epoch 7/10
1875/1875 [==============================] - 1s 656us/step - loss: 0.0593 - accuracy: 0.9805
Epoch 8/10
1875/1875 [==============================] - 1s 653us/step - loss: 0.0527 - accuracy: 0.9823
Epoch 9/10
1875/1875 [==============================] - 1s 653us/step - loss: 0.0477 - accuracy: 0.9844
Epoch 10/10
1875/1875 [==============================] - 1s 654u

In [24]:
model.evaluate(x_test, y_test, verbose = 2)

313/313 - 0s - loss: 0.0760 - accuracy: 0.9788 - 195ms/epoch - 623us/step


[0.07603587955236435, 0.9787999987602234]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [25]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.2208977e-08, 5.1359689e-10, 1.0222119e-06, 3.5545387e-04,
        8.3594476e-13, 6.1339495e-10, 3.1637189e-18, 9.9964261e-01,
        3.2343905e-08, 6.4239339e-07],
       [6.5814482e-10, 3.6526501e-07, 9.9999964e-01, 8.9052801e-09,
        1.9452352e-21, 3.2818310e-12, 7.5406278e-11, 9.4480208e-19,
        2.4019285e-11, 8.5134172e-22],
       [9.2007862e-10, 9.9968576e-01, 8.4192525e-06, 1.6895504e-07,
        4.9494706e-06, 7.2912670e-08, 1.0919971e-06, 2.3207550e-04,
        6.7374996e-05, 3.3978917e-10],
       [9.9993765e-01, 1.7665510e-12, 5.9726994e-05, 1.7186187e-09,
        2.9004694e-09, 1.6915941e-08, 2.8466926e-07, 1.9800829e-07,
        2.2946398e-09, 2.1962142e-06],
       [6.4903554e-09, 7.8881231e-14, 2.2413101e-08, 1.4121031e-11,
        9.9988234e-01, 7.8005796e-11, 5.8829275e-09, 1.9136567e-06,
        2.4136937e-10, 1.1571900e-04]], dtype=float32)>